# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vla_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC,
                                                6, 31, 1, '',
                                                'vla_service.proto')
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

_SERIALIZED_PB = (
    b'\n\x11vla_service.proto\x12\x07\x66luxvla'
    b'\"\xb3\x02\n\x0bObservation'
    b'\x12\x30\n\x06images\x18\x01 \x03(\x0b\x32 '
    b'.fluxvla.Observation.ImagesEntry'
    b'\x12\x30\n\x06\x61rrays\x18\x02 \x03(\x0b\x32 '
    b'.fluxvla.Observation.ArraysEntry'
    b'\x12\x32\n\x07strings\x18\x03 \x03(\x0b\x32!'
    b'.fluxvla.Observation.StringsEntry'
    b'\x1a-\n\x0bImagesEntry\x12\x0b\n\x03key\x18\x01 '
    b'\x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01'
    b'\x1a-\n\x0b\x41rraysEntry\x12\x0b\n\x03key\x18\x01 '
    b'\x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01'
    b'\x1a.\n\x0cStringsEntry\x12\x0b\n\x03key\x18\x01 '
    b'\x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01'
    b'\"M\n\x14PredictActionRequest'
    b'\x12!\n\x03obs\x18\x01 \x01(\x0b\x32\x14.fluxvla.Observation'
    b'\x12\x12\n\nunnorm_key\x18\x02 \x01(\t'
    b'\"O\n\x15PredictActionResponse'
    b'\x12\x13\n\x0b\x61\x63tion_data\x18\x01 \x01(\x0c'
    b'\x12\x12\n\ninfer_time\x18\x02 \x01(\x01'
    b'\x12\r\n\x05\x65rror\x18\x03 \x01(\tb\x06proto3')
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(_SERIALIZED_PB)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vla_service_pb2',
                                        _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_OBSERVATION_IMAGESENTRY']._loaded_options = None
    _globals['_OBSERVATION_IMAGESENTRY']._serialized_options = b'8\001'
    _globals['_OBSERVATION_ARRAYSENTRY']._loaded_options = None
    _globals['_OBSERVATION_ARRAYSENTRY']._serialized_options = b'8\001'
    _globals['_OBSERVATION_STRINGSENTRY']._loaded_options = None
    _globals['_OBSERVATION_STRINGSENTRY']._serialized_options = b'8\001'
    _globals['_OBSERVATION']._serialized_start = 31
    _globals['_OBSERVATION']._serialized_end = 338
    _globals['_OBSERVATION_IMAGESENTRY']._serialized_start = 198
    _globals['_OBSERVATION_IMAGESENTRY']._serialized_end = 243
    _globals['_OBSERVATION_ARRAYSENTRY']._serialized_start = 245
    _globals['_OBSERVATION_ARRAYSENTRY']._serialized_end = 290
    _globals['_OBSERVATION_STRINGSENTRY']._serialized_start = 292
    _globals['_OBSERVATION_STRINGSENTRY']._serialized_end = 338
    _globals['_PREDICTACTIONREQUEST']._serialized_start = 340
    _globals['_PREDICTACTIONREQUEST']._serialized_end = 417
    _globals['_PREDICTACTIONRESPONSE']._serialized_start = 419
    _globals['_PREDICTACTIONRESPONSE']._serialized_end = 498
# @@protoc_insertion_point(module_scope)
